### PR TITLE
Feature/clang format automation

### PR DESCRIPTION
**Pull request by lmoureaux**

### CODE REVIEW

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Here is a comment

**Comment by lmoureaux** [comment]
Commenting again

**Comment by lmoureaux** [comment]
Commenting again again

**Comment by lmoureaux** [comment]
again again again

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by ec429** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by psampathkumar** [comment]
Auto clang-format

**Comment by psampathkumar** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Comment by lmoureaux** [comment]
Auto clang-format

**Pull request closed without merging**
